// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSfVnCOKuNRqjtAucd79i3VZLGxExNosA',
    appId: '1:785283080321:web:e56225bd344a7a16f72d80',
    messagingSenderId: '785283080321',
    projectId: 'chat-app-a309b',
    authDomain: 'chat-app-a309b.firebaseapp.com',
    storageBucket: 'chat-app-a309b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPk94ULoYfnBcIi3j8Ixl3IXR8dagIZIU',
    appId: '1:785283080321:android:e410478a5ec42782f72d80',
    messagingSenderId: '785283080321',
    projectId: 'chat-app-a309b',
    storageBucket: 'chat-app-a309b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAbyXveGcifadb-CX4aQXT7CT8ayR4WTI',
    appId: '1:785283080321:ios:1691685807f522aef72d80',
    messagingSenderId: '785283080321',
    projectId: 'chat-app-a309b',
    storageBucket: 'chat-app-a309b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAbyXveGcifadb-CX4aQXT7CT8ayR4WTI',
    appId: '1:785283080321:ios:1691685807f522aef72d80',
    messagingSenderId: '785283080321',
    projectId: 'chat-app-a309b',
    storageBucket: 'chat-app-a309b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSfVnCOKuNRqjtAucd79i3VZLGxExNosA',
    appId: '1:785283080321:web:7c7825c3c27bd33ff72d80',
    messagingSenderId: '785283080321',
    projectId: 'chat-app-a309b',
    authDomain: 'chat-app-a309b.firebaseapp.com',
    storageBucket: 'chat-app-a309b.firebasestorage.app',
  );
}
